### ISSUE TITLE
Don't hard code paths

### ISSUE THREAD

**Issue by humphd** [japneetsingh035/ModernSSG#10]
You have some hard-coded paths that should get replaced with variables, eg: https://github.com/japneetsingh035/ModernSSG/blob/main/Sources/ModernSSG/Output.swift#L22

**Comment by humphd** [comment]
See also https://github.com/japneetsingh035/ModernSSG/blob/main/Sources/ModernSSG/stylesheet.swift#L26

**Comment by japneetsingh035** [comment]
This issue has been resolved in the new commit.
