### ISSUE TITLE
Hardcoded input/output directories

### ISSUE THREAD

**Issue by a-rokay** [japneetsingh035/ModernSSG#5]
If a user wants to pass a folder as an argument, the folder *must* be located in "/Desktop/ModernSSG/". If they want to pass a single file, it *must* be in "/Desktop/".

If input was a folder, the default output folder is always "/Desktop/ModernSSG/Dist/", and "/Desktop/" if it was a single file.

These should be relative to the program's location.

**Comment by japneetsingh035** [comment]
I have made changes to for all changes to take place in current directory that will be "/Desktop/ModernSSG/"
