### ISSUE TITLE
Refactor to support typical argument options, flags, etc

### ISSUE THREAD

**Issue by humphd** [japneetsingh035/ModernSSG#8]
I know this was something we discussed on Slack as a feature for post-0.1, but I wanted to file it so you come back to it.  Your command tool should follow the typical way of arguments, subcommands, flags, etc. and it looks like Swift can do this, see https://github.com/apple/swift-argument-parser.

**Comment by japneetsingh035** [comment]
Thank you for noticing! I did work on these however, I had some errors and I am working on these to make them better.

**Comment by japneetsingh035** [comment]
Resolved! Thank you so much! I feel so good after making my code such good! Please feel free to look for any more issues.
